{{- if not .Values.postgres.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "platform-auth.fullname" . }}-postgres
  labels:
    {{- include "platform-auth.postgres.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.postgres.username | b64enc | quote }}
  password: {{ randAlphaNum 24 | b64enc | quote }}
{{- end }}
